name: Deploy 

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies and build Vue app
        run: |
          npm install
          npm run build

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VPS
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SERVER_IP: ${{ secrets.HOST }}
          SERVER_PATH: "/var/www/duplantistrend"
        run: |
          # Create directory if it doesn't exis
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "mkdir -p $SERVER_PATH"
          
          # Copy build files to the server
          scp -o StrictHostKeyChecking=no -r dist/* $SSH_USER@$SERVER_IP:$SERVER_PATH

          # Optionally, restart the server if needed
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "sudo systemctl restart my-vue-app-service"
