name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "/var/www/duplantistrend"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
          scp -o StrictHostKeyChecking=no -r dist/* $SSH_USER@$SERVER_IP:$SERVER_PATH

          # Optionally, restart the server if needed
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "sudo systemctl restart my-vue-app-service"
