name: Deploy Vue.js App

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Copy files to VPS
      env:
        VPS_HOST: ${{ secrets.HOST }}
        VPS_USER: ${{ secrets.USERNAME }}
        VPS_SSH_KEY: ${{ secrets.SSH_KEY }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
      run: |
        echo "${VPS_SSH_KEY}" > private_key
        chmod 600 private_key
        rsync -r --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" dist/ ${VPS_USER}@${VPS_HOST}:${TARGET_DIR}
        rm private_key

    - name: Restart server (optional)
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        echo "${VPS_SSH_KEY}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} 'cd ${TARGET_DIR} && pm2 restart all'  # Modify as per your process manager
        rm private_key

